### ISSUE TITLE
testing DropDownPicker using React native testing library causing TypeError: Cannot read properties of null (reading 'measureInWindow')

### ISSUE THREAD

**Issue by mayankchincholkar** [hossein-zare/react-native-dropdown-picker#630]
This is what I am doing in my component
<DropDownPicker
                testID={'testId'}
                style={styles.dropDown}
                open={open}
                value={value}
                items={items}
                setOpen={setOpen}
                setValue={setValue}
                onSelectItem={(item) => {
                  dispatch(update({ item }))
                }}
                setItems={setItems}
              />

When I am loading this component using RNTL
 await waitFor(() =>
      renderWithProviders(<Component/>, {preloadedState})
    );
and firing an event to open the dropdown
await fireEvent.press(screen.getByTestId('testId'))
I see this error

TypeError: Cannot read properties of null (reading 'measureInWindow')

  at _yield$Promise (/node_modules/react-native-dropdown-picker/src/components/Picker.js:652:37)
    at tryCallTwo (/node_modules/promise/lib/core.js:45:5)
    at doResolve (/node_modules/promise/lib/core.js:200:13)
    at new Promise (/node_modules/promise/lib/core.js:66:3)
    at _callee$ (/node_modules/react-native-dropdown-picker/src/components/Picker.js:651:15)
    at tryCatch (/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke (/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.next (/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:124:21)
    at asyncGeneratorStep (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

can anyone help me with a workaround. I tried spying on useRef to mock the implementation but that does not seem to help

**Comment by mayankchincholkar** [comment]
managed to solve this with the help of this comment
https://github.com/hossein-zare/react-native-dropdown-picker/issues/618#issuecomment-1358605788

sort of a worksaround, but works.
